/*
 * Params.cpp
 *
 *  Created on: Jan 18, 2018
 *      Author: kevin
 */


#include "Params.h"

bool PUBLISH_INSIGHT;
std::string INSIGHT_TOPIC;
std::string INSIGHT_CINFO_TOPIC;
int MAX_VARIANCE_SIZE, MIN_VARIANCE_SIZE;
int FAST_THRESHOLD;
double FAST_BLUR_SIGMA;
double INVERSE_IMAGE_SCALE;
bool ANALYZE_RUNTIME;
int KILL_PAD;
double KLT_MIN_EIGEN;
double MIN_NEW_FEATURE_DIST;
int NUM_FEATURES;
int START_FEATURE_COUNT;
int DANGEROUS_MATURE_FEATURE_COUNT_LEVEL;
int MINIMUM_TRACKABLE_FEATURES;
int FRAME_BUFFER_SIZE;
int MINIMUM_KEYFRAME_COUNT_FOR_OPTIMIZATION;
int MAXIMUM_KEYFRAME_COUNT_FOR_OPTIMIZATION;
double MIN_T2D;
double MAX_DEPTH_UPDATES_PER_FRAME;
double MAXIMUM_REPROJECTION_ERROR;
double MAXIMUM_CANDIDATE_REPROJECTION_ERROR;
double MOBA_CANDIDATE_VARIANCE;
double DEFAULT_POINT_DEPTH;
double DEFAULT_POINT_DEPTH_VARIANCE;
double DEFAULT_POINT_HOMOGENOUS_VARIANCE;
double EPS_SBA;
double EPS_MOBA;
double HUBER_WIDTH;
double BORDER_WEIGHT_EXPONENT;
double MINIMUM_DEPTH_DETERMINANT;
int MOBA_MAX_ITERATIONS;
int SBA_MAX_ITERATIONS;
double MAX_POINT_Z;
double MIN_POINT_Z;
//double MAX_RANGE_PER_DEPTH;
int WINDOW_SIZE;
int MAX_PYRAMID_LEVEL;
std::string ODOM_TOPIC;
std::string POINTS_TOPIC;
std::string ODOM_FRAME;
std::string CAMERA_FRAME;
std::string CAMERA_TOPIC;
std::string BASE_FRAME;
std::string WORLD_FRAME;
bool USE_IMU;
std::string IMU_TOPIC;
std::string IMU_FRAME;

