/*
 * config.h
 *
 *  Created on: Mar 28, 2017
 *      Author: kevin
 */

#ifndef PAUVSI_VIO_INCLUDE_PAUVSI_VIO_CONFIG_H_
#define PAUVSI_VIO_INCLUDE_PAUVSI_VIO_CONFIG_H_


#define ROSCONSOLE_MIN_SEVERITY ROSCONSOLE_SEVERITY_DEBUG
#define SUPER_DEBUG true

#define DEFAULT_MIN_POINT_Z 0.02
#define DEFAULT_MAX_POINT_Z 10

#define DEFAULT_STARTING_SIGMA 1000

#define EPS_SBA 0.0000000001

#define EPS_MOBA 0.0000000001


#endif /* PAUVSI_VIO_INCLUDE_PAUVSI_VIO_CONFIG_H_ */
